version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASES=project
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data: